services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../code/backend/src/schema.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ../data/reduced_dataset/filtered_small.sql:/docker-entrypoint-initdb.d/02_seeds.sql

  frontend:
    build:
      context: ../code/frontend
      dockerfile: ../../deployment/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ../code/frontend/src
          target: /app/src
        - action: rebuild
          path: ../code/frontend/package.json

  backend:
    build:
      context: ../code/backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    env_file:
      - .env
    depends_on:
      - postgres

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 5

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ../data/reduced_dataset/images:/images
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; /usr/bin/mc mb myminio/${MINIO_BUCKET:-uploads}; /usr/bin/mc anonymous set public myminio/${MINIO_BUCKET:-uploads}; /usr/bin/mc cp --recursive /images/ myminio/${MINIO_BUCKET:-uploads}/; exit 0; "

volumes:
  postgres_data:
  minio_data:
