services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../code/backend/src/schema.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./dummy_data/seeds.sql:/docker-entrypoint-initdb.d/02_seeds.sql

  frontend:
    build:
      context: ../code/frontend
      dockerfile: ../../deployment/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ../code/frontend/src
          target: /app/src
        - action: rebuild
          path: ../code/frontend/package.json

  backend:
    build:
      context: ../code/backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/dev_db
    depends_on:
      - postgres

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 5

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./dummy_data/images:/images
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; /usr/bin/mc mb myminio/uploads; /usr/bin/mc anonymous set public myminio/uploads; /usr/bin/mc cp --recursive /images/ myminio/uploads/; exit 0; "

volumes:
  postgres_data:
  minio_data:
